name: Auto Merge Dependabot

on:
  workflow_run:
    workflows:
      - Check
      - 'Integration Test'
    types:
      - completed

jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success' && gihub.actor === github.actor == 'dependabot[bot]' }}
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
