name: Auto Merge Dependabot

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GitHub token
        id: prepare_github_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_MANAGER_APP_ID }}
          private_key: ${{ secrets.REPO_MANAGER_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ steps.prepare_github_token.outputs.token }}
