name: Auto Merge Dependabot

on:
  workflow_run:
    workflows:
      - Check
      - 'Integration Test'
    types:
      - completed

jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success' && gihub.actor === github.actor == 'dependabot[bot]' }}
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GitHub token
        id: prepare_github_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_MANAGER_APP_ID }}
          private_key: ${{ secrets.REPO_MANAGER_PRIVATE_KEY }}
      - name: Merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ steps.prepare_github_token.outputs.token }}
          PRESET: DEPENDABOT_MINOR
